// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sample.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Sample {
  public static partial class SampleService
  {
    static readonly string __ServiceName = "sample.SampleService";

    static readonly grpc::Marshaller<global::Sample.SampleRequest> __Marshaller_sample_SampleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Sample.SampleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Sample.SampleResponse> __Marshaller_sample_SampleResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Sample.SampleResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Sample.SampleRequest, global::Sample.SampleResponse> __Method_Transform = new grpc::Method<global::Sample.SampleRequest, global::Sample.SampleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Transform",
        __Marshaller_sample_SampleRequest,
        __Marshaller_sample_SampleResponse);

    static readonly grpc::Method<global::Sample.SampleRequest, global::Sample.SampleResponse> __Method_Stream = new grpc::Method<global::Sample.SampleRequest, global::Sample.SampleResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Stream",
        __Marshaller_sample_SampleRequest,
        __Marshaller_sample_SampleResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Sample.SampleReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SampleService</summary>
    [grpc::BindServiceMethod(typeof(SampleService), "BindService")]
    public abstract partial class SampleServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Sample.SampleResponse> Transform(global::Sample.SampleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task Stream(grpc::IAsyncStreamReader<global::Sample.SampleRequest> requestStream, grpc::IServerStreamWriter<global::Sample.SampleResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SampleService</summary>
    public partial class SampleServiceClient : grpc::ClientBase<SampleServiceClient>
    {
      /// <summary>Creates a new client for SampleService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SampleServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SampleService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SampleServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SampleServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SampleServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Sample.SampleResponse Transform(global::Sample.SampleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Transform(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Sample.SampleResponse Transform(global::Sample.SampleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Transform, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Sample.SampleResponse> TransformAsync(global::Sample.SampleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransformAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Sample.SampleResponse> TransformAsync(global::Sample.SampleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Transform, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Sample.SampleRequest, global::Sample.SampleResponse> Stream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Stream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Sample.SampleRequest, global::Sample.SampleResponse> Stream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Stream, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SampleServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SampleServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SampleServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Transform, serviceImpl.Transform)
          .AddMethod(__Method_Stream, serviceImpl.Stream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SampleServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Transform, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Sample.SampleRequest, global::Sample.SampleResponse>(serviceImpl.Transform));
      serviceBinder.AddMethod(__Method_Stream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Sample.SampleRequest, global::Sample.SampleResponse>(serviceImpl.Stream));
    }

  }
}
#endregion
